input:
  ab:
    tcpDevice: '192.168.0.1' # IP address of the S7 PLC
    #rack: 0                  # Rack number of the PLC. Defaults to 0
    #slot: 1                  # Slot number of the PLC. Defaults to 1
    timeout: 10             # Timeout in seconds for connections and requests. Default to 10
    #addresses:               # List of addresses to read from
    #  - "DB1.DW20"     # Accesses a double word at location 20 in data block 1
    #  - "DB1.S30.10"   # Accesses a 10-byte string at location 30 in data block 
    addresss:
      - '{"1": [{"node": "ns=2;s=Pressure", "group": "D001", "db": "mssql", "historian": "influx", "sqlSp": "sp_sql_logging"}]}'
      - '{"2": [{"node": "ns=2;s=Temperature", "group": "D002", "db": "mssql", "historian": "influx", "sqlSp": "sp_sql_logging"}]}'
    subscribeEnabled: true
    insecure: true
    taddresss:
      - '{"1": [{"node":"ns=2;s=Pressure", "name": "PressureNodeName"}, {"node": "ns=2;s=Humidity", "name": "HumidityNodeName"}]}'
      - '{"2": [{"node":"ns=2;s=Temperature","name": "TemperatureNodeName"}, {"node": "ns=2;s=Air Quality", "name": "Air Qualit Node Name"}]}'
pipeline:
  processors:
    - bloblang: |
        root.value = this
        root.timestamp_ms = (timestamp_unix_nano() / 1000000).floor()
        root.group = meta("group")
        root.db = meta("db")
        root.historian = meta("historian")
        root.sqlSp = meta("sqlSp")

output:
  mqtt:
    urls:
      - 'localhost:1883'
    topic: 'ia/raw/opcua/'
    client_id: benthos-umh