input:
  abcomm:
    tcpDevice: 'localhost' # IP address of the PLC
    timeout: 10             # Timeout in seconds for connections and requests. Default to 10
    subscriptions:
      - '{"tag_name":"adeZeus_trigger","mqtttopic":"ADE","logging_sql":false,"sql_storeprocedure":"ADE_AB","logging_influx":true,"influx_bucket":"AB_bermudez1_trigger","group":"ADE","name":"ADE","type":"trigger","dataType":"str","condition":["onchnage",">1",true]}'
      - '{"tag_name":"adeZeus_cycleNumber[0]{1}","mqtttopic":"adeZeus_cycleNumber_00","logging_sql":false,"sql_storeprocedure":"ADE_AB","logging_influx":true,"influx_bucket":"AB_bermudez1_subscription","group":"alarms","name":"adeZeus_cycleNumber_00","type":"subscription","dataType":"float"}'
    subscribeEnabled: true
    insecure: true
    tsubscriptions:
      - '"nodes":{"adeZeus_trigger":[{"name":"adeZeus_cycleNumber_00","dataType":"float","tag_name":"adeZeus_cycleNumber[0]{1}"},{"name":"adeZeus_cycleTime_00","dataType":"float","tag_name":"adeZeus_cycleTime[0]{1}"}]}'
pipeline:
  processors:
    - bloblang: |
        root.value = this
        root.timestamp_ms = (timestamp_unix_nano() / 1000000).floor()
        root.group = meta("group")
        root.db = meta("db")
        root.historian = meta("historian")
        root.sqlSp = meta("sqlSp")

output:
  mqtt:
    urls:
      - 'localhost:1883'
    topic: 'ia/raw/opcua/'
    client_id: benthos-umh